# Collision.srv

# Request
string vehicle_name

# Control mode values:
# 0 = manualControl
# 1 = depthHeadingAutopilot
# 2 = headingAutopilot
# 3 = depthAutopilot
int32 mode

---
# Response
bool success
string message