# Request a configuration setting

string device # The device for the configuration. Either a name or a number (as a string)
---
bool successful # If false, the request timed out
string configuration # the current configuration for the device
string message # An optional message, such as an error message
