# Set a configuration setting

string device # The device whose configuration is being set, either a name or a number
string configuration # The new configuration option for the device, either a name or a number
---
bool successful
string message # Either an error message or more specific response. May be from rosflight_io or from the firmware
