#!/usr/bin/env python3

import sys

from map_view.map_view import MapView
from rqt_gui.main import Main

plugin = 'map_view.map_view.MapView'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin, plugin_argument_provider=MapView.add_arguments))
