services:
  rosflight:
    # Build image
    build:
      context: ../../..
      dockerfile: src/rosflight_ros_pkgs/docker/Dockerfile
      args:
        - ROS_DISTRO=${ROS_DISTRO:-lyrical}
        - HOST_UID=${HOST_UID:-1000}
        - USER_SHELL=${USER_SHELL:-/usr/bin/bash}
        # Uncomment the next line when building on an ARM64 device (e.g., Raspberry Pi). Keep ROS_IMAGE's tag consistent with ROS_DISTRO above.
        # - ROS_IMAGE=arm64v8/ros:humble-ros-base

    # Enable interactive shell
    stdin_open: true
    tty: true

    # Mount volumes
    volumes:
      # Workspace
      - ../../..:/rosflight_ws
      # USB devices
      - /dev:/dev
      # Needed for displaying graphics
      - /tmp/.X11-unix:/tmp/.X11-unix:rw

    # Set environment variables
    environment:
      # Needed for displaying graphics
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1

    # Give sudo access for USB devices and graphics
    # NOTE: This is not secure.
    privileged: true

    # Give access to host network
    network_mode: host

    # Give access to host memory, letting local containers avoid network
    ipc: host
