# Parameters for ROSflight software-in-the-loop simulation, based on RMRC Anaconda UAV.
# Authors: Ian Reid and Phil Tokumaru

# Mass and inertia parameters are defined in fixedwing.urdf.xacro.
# Mass: 4.5
# Jx: 0.24855
# Jy: 0.3784
# Jz: 0.618
# Jxz: 0.06

/fixedwing/rosflight_sil:
  ros__parameters:
    rho: 1.2682
    mass: 4.5

    wing_s: .52
    wing_b: 2.08
    wing_c: 0.2350
    wing_M: 50.0
    wing_epsilon: 0.9 # revisit -- may not need this for the calculation
    wing_alpha0: 0.05236
    
    D_prop : 0.381 # prop diameter in m (15 in)
    CT_0 : 0.06288743
    CT_1 : -0.02704452
    CT_2 : -0.31320732
    CQ_0 :  0.00614891
    CQ_1 : -0.0106795
    CQ_2 : -0.011779
    KV : 560.0        # Motor speed constant from datasheet in RPM/V
    KQ : 0.01705                       #((1 /(KV_rpm_per_volt)) *60) / (2 *M_PI) Back-emf constant, KV in V-s/rad, Motor torque constant, KQ in N-m/A
    V_max : 24.0                  # voltage for 6s battery at 4 volts per cell
    R_motor : 0.042              # ohms
    I_0 : 1.5                     # no-load (zero torque) current (A)

    servo_tau: .01
    max_deflection_angle: 40. # Maximum deflection of the control surfaces in degrees.

    # Anaconda done for C_L

    C_L_O: .375
    C_L_alpha: 4.43
    C_L_beta: 0.0
    C_L_p: 0.0
    C_L_q: 1.89
    C_L_r: 0.0
    C_L_delta_a: 0.0
    C_L_delta_e: .09 # Correct sign?
    C_L_delta_r: 0.0

    # Anaconda done for C_D

    C_D_O: 0.045
    C_D_alpha: 0.03 # revisit
    C_D_beta: 0.0 # revisit
    C_D_p: 0.0 # revisit
    C_D_q: 0.0 # revisit
    C_D_r: 0.0 # revisit
    C_D_delta_a: 0.0 # revisit
    C_D_delta_e: 0.09 # revisit
    C_D_delta_r: 0.0 # revisit

    C_ell_O: 0.0
    C_ell_alpha: 0.00
    C_ell_beta: -0.0790
    C_ell_p: -0.5077
    C_ell_q: 0.0
    C_ell_r: 0.1871
    C_ell_delta_a: 0.17 #change back/double check
    C_ell_delta_e: 0.0
    C_ell_delta_r: 0.0024

    C_m_O: 0.01988 # Average of Skyhunter and Aerosonde
    C_m_alpha: -2.008 # Average of Skyhunter and Aerosonde
    C_m_beta: 0.0
    C_m_p: 0.0
    C_m_q: -22.351
    C_m_r: 0.0
    C_m_delta_a: 0.0
    C_m_delta_e: -.99 # Leaving this as is but not verified.
    C_m_delta_r: 0.0

    C_n_O: 0.0
    C_n_alpha: 0.0
    C_n_beta: 0.1301
    C_n_p: -0.0364
    C_n_q: 0.0
    C_n_r: -0.1541
    C_n_delta_a: -0.011
    C_n_delta_e: 0.0
    C_n_delta_r: -0.069 #check the sign on this

    # Anaconda done for C_Y

    C_Y_O: 0.0
    C_Y_alpha: 0.00
    C_Y_beta: -0.84
    C_Y_p: 0.0700
    C_Y_q: 0.0
    C_Y_r: 0.0
    C_Y_delta_a: 0.075 #check the sign on this
    C_Y_delta_e: 0.0
    C_Y_delta_r: .2 #check the sign on this
