# Parameters for ROSflight software-in-the-loop simulation, based on RMRC Anaconda UAV.
# Authors: Ian Reid, Phil Tokumaru and Joseph Ritchie

# Mass and inertia parameters are defined in fixedwing.urdf.xacro.
#Mass: 4.524  #orig Mass: 4.5
#Jx .27   #orig Jx: 0.24855
#Jy .367  #orig Jy: 0.3784
#Jz .638  #orig Jz: 0.618
#Jxz .057  #orig Jxz: 0.06
#cgx .089 behind wing LE
#cgy 0 from leading edge wing
#cgz .051m below wing leading edge 
#start alpha is 3deg up, wing geo up 2 deg, tail up 1.25 deg (best trimmmed state)
#trim at about 15 m/s 
#static margin 15.5%
#reynolds number 300000 
#mach .04

#conventions, roll left (negative roll), pitch down, yaw left (positive?)

#OpenVSP test

/**:
  ros__parameters:
    rho: 1.204 
    mass: 4.524
    wing_s: .474 
    wing_b: 2.018 
    wing_c: .241 
    wing_M: 50.0
    wing_epsilon: 0.9 
    wing_alpha0: .05236 #3 deg in rad
    
    # dont edit
    D_prop : 0.381 # prop diameter in m (15 in)
    CT_0 : 0.06288743
    CT_1 : -0.02704452
    CT_2 : -0.31320732
    CQ_0 :  0.00614891
    CQ_1 : -0.0106795
    CQ_2 : -0.011779
    KV : 560.0        # Motor speed constant from datasheet in RPM/V
    KQ : 0.01705      # ((1 /(KV_rpm_per_volt)) *60) / (2 *M_PI) Back-emf constant, KV in V-s/rad, Motor torque constant, KQ in N-m/A
    V_max : 24.0      # voltage for 6s battery at 4 volts per cell
    R_motor : 0.042   # ohms
    I_0 : 1.5         # no-load (zero torque) current (A)
    servo_tau: .01

    C_L_O: .623 
    C_L_alpha: 5.06686 
    C_L_beta: .00017 
    C_L_p: -0.0032795 
    C_L_q: 7.8676829 
    C_L_r: .00023 
    C_L_delta_a: -0.0169216 
    C_L_delta_e: 0.4522919 
    C_L_delta_r: -0.0011681 

    C_D_O: 0.0339017 
    C_D_alpha: 0.2959908 
    C_D_beta: 0.0004163 
    C_D_p: 0.0345 
    C_D_q:  0.261925 
    C_D_r: -0.0035853 
    C_D_delta_a: 0.0018376 
    C_D_delta_e: 0.0265891
    C_D_delta_r: 0.0016033 

    C_ell_O: -0.0000388 
    C_ell_alpha: -0.0001263 
    C_ell_beta:  -0.0019502 
    C_ell_p: -0.525495 
    C_ell_q:  -0.0083974 
    C_ell_r: 0.1099468 
    C_ell_delta_a: 0.1635 
    C_ell_delta_e: -0.0000603 
    C_ell_delta_r: -0.0105643 

    C_m_O: -0.0103936 
    C_m_alpha: -0.8643947 
    C_m_beta: -0.040988 
    C_m_p: -0.0050803 
    C_m_q: -13.5973378  
    C_m_r: 0.0019695 
    C_m_delta_a: 0.0067418 
    C_m_delta_e: -0.75 
    C_m_delta_r: 0.0003607 

    C_n_O: -0.0000005 
    C_n_alpha: 0.0026822 
    C_n_beta:  0.059947 
    C_n_p: -0.0797711 
    C_n_q: 0.0012396 
    C_n_r: -0.1 
    C_n_delta_a: 0.0 
    C_n_delta_e: 0.0000395 
    C_n_delta_r: -0.035 

    C_Y_O: 0.0000003 
    C_Y_alpha: -0.0063057 
    C_Y_beta:  -0.167815 
    C_Y_p: 0.0489344 
    C_Y_q: -0.0033798 
    C_Y_r:  0.1296921 
    C_Y_delta_a: -0.0002552 
    C_Y_delta_e: -0.0001251 
    C_Y_delta_r: 0.17874
