#!/usr/bin/python

# author: James Jackson

import time
import rospy
from rosflight_msgs.msg import Command
import pygame

rospy.init_node('command_joy')
command_pub = rospy.Publisher('command', Command, queue_size=10)

pygame.display.init()
pygame.joystick.init()

joy = pygame.joystick.Joystick(0)
joy.init()

print "joystick", joy.get_name()

# Main event loop
next_update_time = time.time()
while not rospy.is_shutdown():
    pygame.event.pump()

    # 50 Hz update
    if time.time() > next_update_time:
        next_update_time += 0.02

        msg = Command()
        msg.header.stamp = rospy.Time.now()

        msg.mode = 2

        msg.x = joy.get_axis(1) * 0.785
        msg.y = joy.get_axis(2) * 0.785
        msg.z = joy.get_axis(4) * 1.507
        msg.F = joy.get_axis(0) * 0.5 + 0.5

        msg.ignore = 0
        command_pub.publish(msg)
