#! /usr/bin/env python

import rospy
from fcu_common.msg import FW_State

def stateCallback(data):
    chi = data.chi
    while chi > 3.14159:
        chi = chi - 3.1415927
    while chi < -3.14159:
        chi = chi + 3.1415927
    rospy.loginfo(chi)

if __name__ == '__main__':
    rospy.init_node('course')
    rospy.Subscriber("/state", FW_State, stateCallback)

    rospy.spin()
